### PR TITLE
awDwoAeq: Create ability to send event using Event Emitter

### PR DESCRIPTION
**Pull request by chrisclayson**
Ability to load encrypted events in any specified queue. Two commands exist,
one to load a single event create using command line parameters, another to add
events from a JSON file.

See README.md for all details

### CODE REVIEW

**Comment by chrisclayson** [comment]
[Add events to SQS queue from Event Emitter](https://trello.com/c/awDwoAeq/191-add-events-to-sqs-queue-from-event-emitter)

**Review by alexandergeegds — CHANGES_REQUESTED** [review]
We need to stop ignoring `/gradle/` and make sure the `gradle-wrapper.jar` and `gradle-wrapper.properties` files are in vcs for calls to `./gradlew` to work.

I also, for obvious reasons, can't test actually sending, but I've disabled emitting via configuration file and everything else seems to work, and looks reasonable to me.

**Comment by chrisclayson** [comment]
Good point, well made ... was a bit overzealous by ignoring it.

**Review by alexandergeegds — APPROVED** [review]

**Review by brenetic — APPROVED** [review]
🚀

**Pull request merged**
